version: "3.7"

services:
  db:
    container_name: my-db-container
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=movietrailer
      - LC_ALL=C.UTF-8
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - frontend
  app:
    container_name: my-web-container
    build: .
    environment:
      - SECRET_KEY=lasfoisu8u32rohjf8uy9rhoi2f
      - DATABASE_URL=postgres://admin:admin@db:5432/movietrailer
      - DEBUG=False
      - ALLOWED_HOSTS=*
      - USER_ADMIN_EMAIL=admin@admin.com
      - USER_ADMIN_PASS=1qaz2wsx3edc
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
    networks:
      - frontend
networks:
  frontend: