# Generated by Django 2.1.1 on 2018-09-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('storyline', models.TextField()),
                ('poster_image_url', models.URLField(max_length=300)),
                ('trailer_youtube_url', models.URLField(max_length=300)),
            ],
        ),
    ]
